// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8mG1SaKFtQRx7RpJP73PJcP7otE2Qnk',
    appId: '1:609105856433:web:d54a826e40caf0ab8bdf90',
    messagingSenderId: '609105856433',
    projectId: 'bconnect-ded53',
    authDomain: 'bconnect-ded53.firebaseapp.com',
    storageBucket: 'bconnect-ded53.firebasestorage.app',
    measurementId: 'G-V70PLNWF8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkHjalRry4kNDpd7oHaLzDdsvBonAOCc',
    appId: '1:609105856433:android:a847497994c70aba8bdf90',
    messagingSenderId: '609105856433',
    projectId: 'bconnect-ded53',
    storageBucket: 'bconnect-ded53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3TF9aUtro_zrQW7xxScIDO3MRwTyVhw',
    appId: '1:609105856433:ios:a07a89aef97ecba88bdf90',
    messagingSenderId: '609105856433',
    projectId: 'bconnect-ded53',
    storageBucket: 'bconnect-ded53.firebasestorage.app',
    iosBundleId: 'com.bconnect.chat.bConnectTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK3TF9aUtro_zrQW7xxScIDO3MRwTyVhw',
    appId: '1:609105856433:ios:a07a89aef97ecba88bdf90',
    messagingSenderId: '609105856433',
    projectId: 'bconnect-ded53',
    storageBucket: 'bconnect-ded53.firebasestorage.app',
    iosBundleId: 'com.bconnect.chat.bConnectTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8mG1SaKFtQRx7RpJP73PJcP7otE2Qnk',
    appId: '1:609105856433:web:5f7c38e2e94b0e678bdf90',
    messagingSenderId: '609105856433',
    projectId: 'bconnect-ded53',
    authDomain: 'bconnect-ded53.firebaseapp.com',
    storageBucket: 'bconnect-ded53.firebasestorage.app',
    measurementId: 'G-Y0NQRVPSW9',
  );
}
